language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: required

before_install:
   - sudo apt-get install libffi-dev python-cffi pypy python3-cffi
   - export PATH=$HOME/gopath/bin:/usr/local/bin:$PATH
   # Init() in main_test will make sure all backends are available if
   # GOPY_TRAVIS_CI is set
   - export GOPY_TRAVIS_CI=1
   # make python output (sys.stdout, sys.stderr) unbuffered
   - export PYTHONUNBUFFERED=1
   # temporary workaround for go-python/gopy#83
   - export GODEBUG=cgocheck=0
   # pypy3 isn't packaged in ubuntu yet.
   - TEMPDIR=$(mktemp -d)
   - curl -L https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.10.0-linux_x86_64-portable.tar.bz2 --output $TEMPDIR/pypy3.tar.bz2
   - tar xf $TEMPDIR/pypy3.tar.bz2 -C $TEMPDIR
   - sudo ln -s $TEMPDIR/pypy3.5-5.10.0-linux_x86_64-portable/bin/pypy3 /usr/local/bin/pypy3

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
