language: go

go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: required

before_install:
   - sudo apt-get install libffi-dev python-cffi python3-cffi
   - export PATH=$HOME/gopath/bin:/usr/local/bin:$PATH
   # Init() in main_test will make sure all backends are available if
   # GOPY_TRAVIS_CI is set
   - export GOPY_TRAVIS_CI=1
   - export GOTRACEBACK=crash
   # make python output (sys.stdout, sys.stderr) unbuffered
   - export PYTHONUNBUFFERED=1
   # temporary workaround for go-python/gopy#83
   - export GODEBUG=cgocheck=0
   # pypy3 isn't packaged in ubuntu yet.
   - TEMPDIR=$(mktemp -d)
   - export PYPYVERSION=v6.0.0
   - curl -L https://bitbucket.org/pypy/pypy/downloads/pypy2-${PYPYVERSION}-linux64.tar.bz2 --output $TEMPDIR/pypy2.tar.bz2
   - curl -L https://bitbucket.org/pypy/pypy/downloads/pypy3-${PYPYVERSION}-linux64.tar.bz2 --output $TEMPDIR/pypy3.tar.bz2
   - tar xf $TEMPDIR/pypy2.tar.bz2 -C $TEMPDIR
   - tar xf $TEMPDIR/pypy3.tar.bz2 -C $TEMPDIR
   - sudo ln -s $TEMPDIR/pypy2-$PYPYVERSION-linux64/bin/pypy  /usr/local/bin/pypy
   - sudo ln -s $TEMPDIR/pypy3-$PYPYVERSION-linux64/bin/pypy3 /usr/local/bin/pypy3
   # install goimports
   - go get golang.org/x/tools/cmd/goimports

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
